name: Build OpenWrt Kernel BPF CO-RE

on:
  workflow_dispatch:
  repository_dispatch:
    types: [vmlinux]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies (kernel build + pahole)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            libncurses-dev \
            zlib1g-dev \
            jq \
            curl \
            xz-utils \
            patch \
            git \
            dwarves

      - name: Fetch latest OpenWrt v25.x tag
        run: |
          openwrt_version=$(curl -s "https://api.github.com/repos/openwrt/openwrt/tags" \
            | jq -r '[ .[].name | select(startswith("v25")) ][0]')
          echo "openwrt_version=$openwrt_version" >> $GITHUB_ENV

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt \
            -b "${{ env.openwrt_version }}" --depth=1

      - name: Extract kernel version from OpenWrt
        run: |
          kernel_version=$(awk 'match($0,/LINUX_VERSION-([0-9]+\.[0-9]+) = \.([0-9]+)/,m){print m[1]"."m[2]}' \
            openwrt/target/linux/generic/kernel-6.12)
          echo "kernel_version=$kernel_version" >> $GITHUB_ENV

      - name: Download Linux kernel tarball
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ env.kernel_version }}.tar.xz
          tar Jxf linux-${{ env.kernel_version }}.tar.xz
          rm -rf 

      - name: Extract kernel code
        run: |
          tar Jxf linux-${{ env.kernel_version }}.tar.xz

      - name: Copy OpenWrt generic files
        run: |
          cp -a openwrt/target/linux/generic/files/* linux-${{ env.kernel_version }}/

      - name: Apply OpenWrt patches
        run: |
          cd linux-${{ env.kernel_version }}
          for p in ../openwrt/target/linux/generic/backport-6.12/*.patch; do
              patch -p1 -i "$p"
          done
          for p in ../openwrt/target/linux/generic/pending-6.12/*.patch; do
              patch -p1 -i "$p"
          done
          for p in ../openwrt/target/linux/generic/hack-6.12/*.patch; do
              patch -p1 -i "$p"
          done

      - name: Download OpenWrt musl toolchain
        run: |
          wget https://github.com/sbwml/package_kernel_vmlinux-btf/releases/download/toolchain/config.aarch64_generic
          wget https://github.com/sbwml/package_kernel_vmlinux-btf/releases/download/toolchain/toolchain-aarch64_generic_gcc-14.3.0_musl.tar.xz
          tar xf toolchain-aarch64_generic_gcc-14.3.0_musl.tar.xz && rm -rf toolchain-aarch64_generic_gcc-14.3.0_musl.tar.xz
          wget https://github.com/sbwml/package_kernel_vmlinux-btf/releases/download/toolchain/config.x86_64
          wget https://github.com/sbwml/package_kernel_vmlinux-btf/releases/download/toolchain/toolchain-x86_64_gcc-14.3.0_musl.tar.xz
          tar xf toolchain-x86_64_gcc-14.3.0_musl.tar.xz && rm -rf toolchain-x86_64_gcc-14.3.0_musl.tar.xz
          mkdir vmlinux-btf-${{ env.kernel_version }}

      - name: Build Kernel vmlinux (aarch64_generic)
        run: |
          export PATH="$(realpath toolchain-aarch64_generic_gcc-14.3.0_musl/bin):$PATH"
          export STAGING_DIR="$(realpath toolchain-aarch64_generic_gcc-14.3.0_musl)"
          export CPLUS_INCLUDE_PATH="$(realpath toolchain-aarch64_generic_gcc-14.3.0_musl/include)"
          export ARCH=arm64 CROSS_COMPILE=aarch64-openwrt-linux-musl-
          mkdir aarch64_generic
          cp config.aarch64_generic aarch64_generic/.config
          cd linux-${{ env.kernel_version }}
          make O=../aarch64_generic olddefconfig
          make O=../aarch64_generic headers_install
          make O=../aarch64_generic -j$(($(nproc) + 1)) vmlinux
          pahole --btf_encode_detached ../vmlinux-btf-${{ env.kernel_version }}/vmlinux-${{ env.kernel_version }}-aarch64_generic ../aarch64_generic/vmlinux

      - name: Build Kernel vmlinux (x86_64)
        run: |
          export PATH="$(realpath toolchain-x86_64_gcc-14.3.0_musl/bin):$PATH"
          export STAGING_DIR="$(realpath toolchain-x86_64_gcc-14.3.0_musl)"
          export CPLUS_INCLUDE_PATH="$(realpath toolchain-x86_64_gcc-14.3.0_musl/include)"
          export ARCH=x86 CROSS_COMPILE=x86_64-openwrt-linux-musl-
          mkdir x86_64
          cp config.x86_64 x86_64/.config
          cd linux-${{ env.kernel_version }}
          make O=../x86_64 olddefconfig
          make O=../x86_64 headers_install
          make O=../x86_64 -j$(($(nproc) + 1)) vmlinux
          pahole --btf_encode_detached ../vmlinux-btf-${{ env.kernel_version }}/vmlinux-${{ env.kernel_version }}-x86_64 ../x86_64/vmlinux

      - name: Package vmlinux btf file
        run: |
          tar Jcvf vmlinux-btf-${{ env.kernel_version }}.tar.xz vmlinux-btf-${{ env.kernel_version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vmlinux-${{ env.kernel_version }}
          path: |
            vmlinux-btf-${{ env.kernel_version }}/vmlinux-*

      - name: Create release
        uses: ncipollo/release-action@v1.20.0
        with:
          name: ${{ env.openwrt_version }}
          allowUpdates: true
          tag: ${{ env.openwrt_version }}
          commit: openwrt-25.12
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            vmlinux-btf-${{ env.kernel_version }}.tar.xz
